'use client';
import Link from 'next/link';
import {useState} from 'react';

function Header(){return <header className="header"><div className="container nav"><Link className="logo" href="/">Mi Bendición</Link><nav className="links"><Link href="/">Home</Link><Link href="/#about">About Us</Link><Link href="/#program">Our Program</Link><Link href="/#spanish">Spanish Learning</Link><Link href="/#meals">Meals</Link><Link href="/#faq">FAQ</Link></nav><Link className="btn btn-rust" href="/contact">Enrollment / Contact</Link></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><div className="logo">Mi Bendición</div><p><em>Growing with love, learning with purpose, shining with excellence.</em></p><p>Mason, Ohio<br/>Monday–Friday | 6:00 AM – 6:00 PM<br/>childcare@guarderiamiBendicion.com</p></div><div><h4>Explore</h4><p><Link href="/">Home</Link><br/><Link href="/#about">About Us</Link><br/><Link href="/#program">Our Program</Link><br/><Link href="/#spanish">Spanish Learning</Link></p></div><div><h4>Quick Links</h4><p><Link href="/contact">Contact</Link><br/><Link href="/privacy">Privacy Policy</Link></p></div><div><h4>Contact</h4><Link className="btn btn-rust" href="/contact">Schedule a Visit</Link></div></div><div className="container copyright">© 2026 Guardería Mi Bendición · Mi Bendición Daycare. All rights reserved.</div></footer>}

export default function Contact(){const[status,setStatus]=useState('');async function submit(e){e.preventDefault();setStatus('Sending…');const data=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/inquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});setStatus(r.ok?'Thank you! Your message has been sent.':'Something went wrong. Please try again.');if(r.ok)e.currentTarget.reset();}
return <><Header/><section className="contact-hero"><div className="container"><div className="eyebrow">Contact</div><h1 style={{fontSize:48}}>Let's Talk About Child Care</h1><p className="lead" style={{maxWidth:720}}>Choosing childcare is an important decision. Contact Mi Bendición Daycare to learn more about our program, ask about current availability, child care vouchers, or schedule a visit.</p></div></section><section className="section"><div className="container contact-grid"><aside className="contact-card"><h4>Location</h4><p><strong>Mason, Ohio</strong></p><hr/><h4>Hours</h4><p><strong>Monday–Friday · 6:00 AM–6:00 PM</strong></p><hr/><h4>Email</h4><p><strong>childcare@guarderiamiBendicion.com</strong></p><hr/><a className="btn btn-light" style={{width:'100%'}} href="#form">Schedule a Visit</a></aside><div id="form" className="form-card"><h2 style={{fontSize:30,marginBottom:24}}>Send us a message</h2><form onSubmit={submit} className="form-grid"><div className="field"><label>Parent/Guardian Name *</label><input required name="name" placeholder="Jane Doe"/></div><div className="field"><label>Email *</label><input required type="email" name="email" placeholder="jane@email.com"/></div><div className="field"><label>Phone</label><input name="phone" placeholder="(513) 555-0100"/></div><div className="field"><label>Child's Age</label><input name="childAge" placeholder="2 years"/></div><div className="field"><label>Desired Start Date</label><input type="date" name="startDate"/></div><div className="field"><label>Days of Care Needed</label><input name="days" placeholder="Mon–Fri"/></div><div className="field full"><label>Are you using child care assistance/vouchers?</label><select name="assistance"><option value="">—</option><option>Yes</option><option>No</option><option>Not sure</option></select></div><div className="field full"><label>Message *</label><textarea required name="message" placeholder="Tell us how we can help..."/></div><div className="field full"><button className="btn btn-rust" type="submit">Send Message</button><div className="status">{status}</div></div></form></div></div></section><Footer/></>}
