import Link from 'next/link';

function Header(){return <header className="header"><div className="container nav"><div className="logo">Mi Bendición</div><nav className="links"><a href="#about">About Us</a><a href="#program">Our Program</a><a href="#spanish">Spanish Learning</a><a href="#meals">Meals</a><a href="#faq">FAQ</a></nav><Link className="btn btn-rust" href="/contact">Enrollment / Contact</Link></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><div className="logo">Mi Bendición</div><p><em>Growing with love, learning with purpose, shining with excellence.</em></p><p>Mason, Ohio<br/>Monday–Friday | 6:00 AM – 6:00 PM<br/>childcare@guarderiamiBendicion.com</p></div><div><h4>Explore</h4><p><a href="#about">About Us</a><br/><a href="#program">Our Program</a><br/><a href="#spanish">Spanish Learning</a><br/><a href="#meals">Meals</a><br/><a href="#faq">FAQ</a></p></div><div><h4>Quick Links</h4><p><Link href="/contact">Contact</Link><br/><Link href="/privacy">Privacy Policy</Link></p></div><div><h4>Contact</h4><Link className="btn btn-rust" href="/contact">Schedule a Visit</Link></div></div><div className="container copyright">© 2026 Guardería Mi Bendición · Mi Bendición Daycare. All rights reserved.</div></footer>}

export default function Home(){return <><Header/><main>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Home childcare · Mason, Ohio</div><h1>A Loving Place to Learn, Grow & <span className="accent">Shine</span></h1><p className="lead">A nurturing home environment focused on early learning, Spanish exposure, meaningful play, and personalized care.</p><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Link href="/contact" className="btn btn-rust">Schedule a Visit</Link><a href="#program" className="btn btn-light">Explore Our Program</a></div><div className="stats"><div className="stat"><strong>Home-based care</strong><span>Warm & personal</span></div><div className="stat"><strong>Bilingual exposure</strong><span>English + Spanish</span></div><div className="stat"><strong>Purposeful learning</strong><span>Play-led growth</span></div></div></div><div className="hero-card"><div className="hero-art">🧒🧱👧<small>Play · Learn · Grow</small></div></div></div></section>
<section id="about" className="section cream"><div className="container center"><div className="eyebrow">About us</div><h2>A Nurturing Home<br/>Where Children Thrive</h2><p className="sub">We provide a loving, structured environment that supports the whole child through relationships, routines, learning experiences, and individual attention.</p><div className="cards"><div className="card"><div className="icon">💗</div><h3>Safe & Loving</h3><p>A caring home atmosphere where children feel secure and known.</p></div><div className="card"><div className="icon">🌱</div><h3>Whole-Child Growth</h3><p>Social, emotional, cognitive, language, and physical development.</p></div><div className="card"><div className="icon">🎨</div><h3>Purposeful Play</h3><p>Hands-on activities that build confidence and curiosity.</p></div><div className="card"><div className="icon">🤝</div><h3>Family Partnership</h3><p>Open communication and collaboration with parents.</p></div></div></div></section>
<section className="section blush"><div className="container center"><div className="eyebrow">Experience</div><h2>More than 30 years of caring for children</h2><p className="sub">Experience matters, but so does the heart behind the work. Our program blends consistency, warmth, and a genuine love for children.</p><div className="quote">“Every child deserves patience, belonging, encouragement, and a place where they can become confident in who they are.”</div></div></section>
<section id="program" className="section blue"><div className="container center"><div className="eyebrow">Our program</div><h2>Learning Through Play & Purpose</h2><p className="sub">A balanced day of guided learning, movement, creativity, exploration, rest, and social connection.</p><div className="pills"><span className="pill">Fine Motor</span><span className="pill">Sensory Play</span><span className="pill">Early Math</span><span className="pill">Music</span><span className="pill">Art</span><span className="pill">Story Time</span><span className="pill">Outdoor Play</span><span className="pill">Social Skills</span><span className="pill">Language</span></div></div></section>
<section id="spanish" className="section cream"><div className="container center"><div className="eyebrow">Spanish learning</div><h2>Spanish as a Second Language</h2><p className="sub">Children are introduced naturally to Spanish through songs, vocabulary, conversation, books, routines, and play.</p><div className="pills"><span className="pill">Hola</span><span className="pill">Colores</span><span className="pill">Números</span><span className="pill">Familia</span><span className="pill">Animales</span><span className="pill">Canciones</span></div></div></section>
<section className="section"><div className="container center"><div className="eyebrow">Daily rhythm</div><h2>A predictable day that<br/>balances learning & rest</h2><div className="timeline"><div className="item"><strong>Arrival & Free Play</strong><p>Warm welcome and gentle transition into the day.</p></div><div className="item"><strong>Morning Learning</strong><p>Stories, language, early concepts, music, and movement.</p></div><div className="item"><strong>Lunch & Rest</strong><p>Nutritious meals followed by quiet time and naps.</p></div><div className="item"><strong>Afternoon Exploration</strong><p>Art, sensory activities, outdoor time, and social play.</p></div></div></div></section>
<section id="meals" className="section peach"><div className="container center"><div className="eyebrow">Meals & nutrition</div><h2>Planned, nutritious<br/>and age-appropriate</h2><p className="sub">Meals and snacks are planned to support growing children while establishing healthy routines.</p><div className="cards"><div className="card"><div className="icon">🍳</div><h3>Breakfast</h3></div><div className="card"><div className="icon">🍎</div><h3>Morning Snack</h3></div><div className="card"><div className="icon">🥗</div><h3>Lunch</h3></div><div className="card"><div className="icon">🍊</div><h3>Afternoon Snack</h3></div></div></div></section>
<section className="section"><div className="container"><div className="dark-panel"><div className="eyebrow">Licensed home childcare</div><h3>Child Care Assistance Welcome</h3><p>Families using eligible childcare assistance programs are welcome to contact us about availability and enrollment.</p></div></div></section>
<section className="section blush"><div className="container center"><div className="eyebrow">Why families choose us</div><h2>What makes our home<br/>daycare different</h2><div className="cards"><div className="card"><h3>Small-group care</h3><p>More individual attention and stronger relationships.</p></div><div className="card"><h3>Consistent routines</h3><p>Children thrive when they know what to expect.</p></div><div className="card"><h3>Learning every day</h3><p>Development happens naturally through meaningful experiences.</p></div><div className="card"><h3>Family communication</h3><p>Parents stay informed and involved.</p></div></div></div></section>
<section className="section"><div className="container"><div className="cta"><div className="eyebrow" style={{color:'#ffe0d3'}}>Enrollment</div><h2>Join the Mi Bendición Family</h2><p>Have questions about availability or your child's needs? We'd love to hear from you.</p><Link href="/contact" className="btn btn-light">Schedule a Visit</Link></div></div></section>
<section id="faq" className="section blush"><div className="container center"><div className="eyebrow">Frequently asked questions</div><h2>Questions families often ask</h2><div className="faq"><details open><summary>Where are you located?</summary><p>We are a home-based childcare program located in Mason, Ohio.</p></details><details><summary>What are your hours?</summary><p>Monday through Friday, 6:00 AM to 6:00 PM.</p></details><details><summary>Do you offer Spanish learning?</summary><p>Yes. Spanish is introduced naturally through everyday activities and routines.</p></details><details><summary>Do you accept childcare assistance?</summary><p>Please contact us so we can discuss eligibility and availability.</p></details><details><summary>How do I schedule a visit?</summary><p>Use our contact form and we will follow up with you directly.</p></details></div></div></section>
</main><Footer/></>}
